---
# 1) Create the Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: node-test-app-yellow

---
# 2) Create the Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-app-yellow-deployment
  namespace: node-test-app-yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-test-app-yellow
  template:
    metadata:
      labels:
        app: node-test-app-yellow
    spec:
      containers:
        - name: node-test-app-yellow-container
          # Replace with your container image that listens on port 80
          image: bahajian/node_test_app:yellow
          ports:
            - containerPort: 80

---
# 3) Create the Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: node-test-app-yellow-service
  namespace: node-test-app-yellow
spec:
  selector:
    app: node-test-app-yellow
  type: LoadBalancer
  ports:
    - port: 80          # Internal cluster port
      targetPort: 80    # Container port
      protocol: TCP
  loadBalancerIP: 192.168.2.200  # Ensure this IP is in MetalLB's range

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
   addresses:
   - 192.168.2.200-192.168.2.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool