name: Build and Push Docker Image on Release

on:
  release:
    types:
      - created  # Trigger workflow when a new release is created
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug event payload
      - name: Debug GitHub Event
        run: cat $GITHUB_EVENT_PATH

      # Extract Release Name or fallback to Tag
      - name: Get Release Name
        run: |
          RELEASE_NAME=$(jq -r '.release.name // empty' $GITHUB_EVENT_PATH | tr ' ' '-')
          if [ -z "$RELEASE_NAME" ]; then
            echo "Release name is missing, using tag name instead."
            RELEASE_NAME=${GITHUB_REF#refs/tags/}
          fi
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node_test_app:${{ env.RELEASE_NAME }}

      - name: Log out from Docker Hub
        run: docker logout